name: projeto_jenice_pay_list
description: Projeto adm de vaquinha.
publish_to: 'Flebersom and Jenice'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #-  - /media/flebersom/KINGSTON/Apps/projeto2/projeto_jenice_pay_list/assets/images/
  #- /media/flebersom/dataOnly/Apps/projeto2/projeto_jenice_pay_list/assets/images/
  #-  - /media/flebersom/KINGSTON/
  