// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8h_9-Ro2-AEMP8srEaci5JNJFrIifHSY',
    appId: '1:460891721947:web:9d6e81ec09265b01987cfe',
    messagingSenderId: '460891721947',
    projectId: 'projeto-vaquinha',
    authDomain: 'projeto-vaquinha.firebaseapp.com',
    storageBucket: 'projeto-vaquinha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeEp-1P61Rwv5zDxySXBKggltGCsu2tLo',
    appId: '1:460891721947:android:96a0a6c84472ef09987cfe',
    messagingSenderId: '460891721947',
    projectId: 'projeto-vaquinha',
    storageBucket: 'projeto-vaquinha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yQnPlcM7daRSC26WY9_iTk7KrICpM7s',
    appId: '1:460891721947:ios:6374dd9c4a8957e5987cfe',
    messagingSenderId: '460891721947',
    projectId: 'projeto-vaquinha',
    storageBucket: 'projeto-vaquinha.appspot.com',
    iosBundleId: 'com.example.projetoJenicePayList',
  );
}
